language: scala
scala:
  - 2.13.4
jdk: openjdk8

before_install:
  - git fetch --tags

stages:
  - name: test

jobs:
  include:
    - stage: test
      name: run tests
      script:
        - sbt scalafmtCheckAll
        - sbt +test
